Algoritmo "sequenciaImpares"
// Leia um valor inteiro X. Em seguida mostre os ímpares de 1 até X,
// um valor por linha, inclusive o X, se for o caso.
Var
// Seção de Declarações das variáveis 

    x, i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

    escreva ("Informe um valor: ")
    leia    (x)

    para i de 1 ate x faca
        se i%2 <> 0 entao
          escreval (i)
        fimse

    fimpara


Fimalgoritmo